services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile.blockchain
    container_name: blockchain
    ports:
      - "8545:8545"
    volumes:
      - contract-artifacts:/app/blockchain/artifacts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - blockchain
    volumes:
      - contract-artifacts:/app/frontend/src/artifacts:ro

  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    ports:
      - "8546:8546"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  contract-artifacts: